### ISSUE TITLE
Unit test failing when modbus not present

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/modbus#17]
We are skipping the test if we don't have `pymodbus3` but the unit test is failing on this `patch`:
https://github.com/nio-blocks/modbus/blob/master/tests/test_modbus_block.py#L97

``` python
Traceback (most recent call last):
  File "/opt/python3.4/lib/python3.4/unittest/mock.py", line 1128, in patched
    arg = patching.__enter__()
  File "/opt/python3.4/lib/python3.4/unittest/mock.py", line 1181, in __enter__
    self.target = self.getter()
  File "/opt/python3.4/lib/python3.4/unittest/mock.py", line 1348, in <lambda>
    getter = lambda: _importer(target)
  File "/opt/python3.4/lib/python3.4/unittest/mock.py", line 1037, in _importer
    thing = __import__(import_path)
ImportError: No module named 'modbus'
```

**Comment by hansmosh** [comment]
@mattdodge Is this from when jenkins runs the unit tests? I can't reproduce this. I tried making a virtual environment, activating that and then running the unit tests with `nose2 modbus.tests -v`. It successfully skips all the tests.

**Comment by mattdodge** [comment]
Yes, it was on Jenkins. Here is a link to a failed build: http://jenkins.nioinstances.com:8081/job/nio_blocks/490/testReport/

Maybe it has something to do with the version of nose that is running? It seems to be running the tests though, not skipping them, so something else might be up.
