### ISSUE TITLE
"Bad Response" errors occuring often

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/modbus#5]
See attached screenshot, there are no apparent issues with re-connection or overall stability, but we are losing samples. Log level was 'not set' at time of screen cap, since then the block has been changed to 'debug' and I have seen no errors in 70 minutes.

![image](https://cloud.githubusercontent.com/assets/8739615/8463694/c3536204-1ff9-11e5-883f-15778d9c8762.png)

**Comment by hansmosh** [comment]
This has been fixed already e2dce67c573d492781b59b8de64f544ad94c999c
